version: "3.7"
services:
  ssr:
    build: .
    image: go-templ-ssr
    container_name: go-templ-container
    restart: always
    environment:
      - MONGODB_URI="mongodb://root:hoplin1234!@db:27017/"
      - MONGODB_DATABASE_NAME="todo"
      - ENV="docker"
    networks:
      - ssr-network
    ports:
      - 8090:8080
  db:
    image: mongo:7.0
    container_name: mongodb-standalone
    restart: always
    networks:
      - ssr-network
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: hoplin1234!
      MONGO_INITDB_DATABASE: todo
    ports:
      - 27017:27017
networks:
  ssr-network:
    driver: bridge
