version: "3.7"
services:
  db:
    image: mongo:7.0
    container_name: mongodb-standalone
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: hoplin1234!
      MONGO_INITDB_DATABASE: golang
    ports:
      - 27017:27017
