branch-defaults:
  circleci:
    environment: Circle-CI-env
environment-defaults:
  Circle-CI-env:
    branch: null
    repository: null
global:
  application_name: Circle-CI
  default_ec2_keyname: hub-key
  default_platform: Go 1 running on 64bit Amazon Linux 2023
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: git
  workspace_type: Application
