version: 2.1
jobs:
  # Build
  build:
    # Execute in linux VM: https://circleci.com/docs/executor-intro/#linux-vm
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run:
        name: Update system
        command: sudo apt-get update
      - run:
        name: Install Python3
        command: sudo apt install python3-pip
      - run:
        name: Update system
        command: sudo pip3 install awsebcli --upgrade
      - persist_to_workspace:
          root: .
          paths:
            - .
  deploy:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - attach_workspace:
        at: .
      - checkout
      - run: aws s3 sync . s3://circle-ci-cicd

workflows:
  build_n_deploy:
    jobs:
      - build
      - deploy
